blueprint:
  name: Frank Energie - V11 (Boost & Rendement)
  description: >
    Slim laden V11.
    
    NIEUW:
    - Boost Modus: Dwing laden af via een knop.
    - Rendementscheck: Laad buffer-uren alleen als het prijsverschil groot genoeg is (percentage).
    - Notificaties: Krijg een berichtje als het laden start.
  domain: automation
  input:
    # --- BASIS ENTITEITEN ---
    battery_reserve_switch:
      name: Reserve mode switch
      description: De schakelaar die laden start.
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: Batterij SoC sensor (%)
      selector:
        entity:
          domain: sensor
          device_class: battery
    frank_price_sensor:
      name: Frank Energie prijs sensor
      selector:
        entity:
          domain: sensor

    # --- NIEUW: BOOST KNOP ---
    boost_switch:
      name: Boost Schakelaar (Optioneel)
      description: Een input_boolean. Als deze AAN staat, wordt er direct geladen (negeert alles).
      default: []
      selector:
        entity:
          domain: input_boolean
          multiple: false

    # --- NIEUW: NOTIFICATIES ---
    notify_device:
      name: Telefoon voor notificaties (Optioneel)
      description: Selecteer je telefoon. Je krijgt een bericht als het laden START.
      default: []
      selector:
        device:
          integration: mobile_app

    # --- ZON & VOORSPELLING ---
    solar_forecast_today:
      name: Zonvoorspelling VANDAAG (kWh)
      selector:
        entity:
          domain: sensor
    solar_forecast_tomorrow:
      name: Zonvoorspelling MORGEN (kWh)
      selector:
        entity:
          domain: sensor
    summer_solar_threshold:
      name: Omschakelpunt Zomer/Winter (kWh)
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "kWh"

    # --- RENDEMENT & MARGES (NIEUW) ---
    min_profit_margin:
      name: Minimaal Rendement (%)
      description: >
        Hoeveel procent moet de prijs lager zijn dan het gemiddelde om 'extra' buffer-uren te laden?
        Dit compenseert laadverliezen. Bijv. 20%.
        Als prijs â‚¬0,25 is en gemiddelde â‚¬0,30 -> (0,30 - 20%) = 0,24. Dan laden we NIET (te duur).
      default: 20
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: "%"
    
    # --- DOELEN & CAPACITEIT ---
    target_soc_winter:
      name: Doel SoC Winter (%)
      default: 90
      selector:
        number:
          min: 10
          max: 100
    target_soc_summer:
      name: Doel SoC Zomer (%)
      default: 30
      selector:
        number:
          min: 10
          max: 100
    battery_capacity_kwh:
      name: Batterij Capaciteit (kWh)
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 0.1
    charge_power_kw:
      name: Normale Laadsnelheid (kW)
      default: 3.0
      selector:
        number:
          min: 0.1
          max: 22
          step: 0.1
    safety_factor:
      name: BMS Vertragingsfactor
      description: 1.5 = 50% extra tijd reserveren voor trage batterijen.
      default: 1.5
      selector:
        number:
          min: 1.0
          max: 4.0
          step: 0.1
    max_price_cap:
      name: Absolute Max Prijs (â‚¬)
      default: 0.35
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.01
    emergency_soc:
      name: Nood SoC (%)
      default: 10
      selector:
        number:
          min: 0
          max: 100

variables:
  battery_reserve_switch: !input battery_reserve_switch
  battery_soc_sensor: !input battery_soc_sensor
  frank_price_sensor: !input frank_price_sensor
  boost_switch: !input boost_switch
  notify_device: !input notify_device
  # Inputs
  solar_forecast_today: !input solar_forecast_today
  solar_forecast_tomorrow: !input solar_forecast_tomorrow
  summer_solar_threshold: !input summer_solar_threshold
  min_profit_margin: !input min_profit_margin
  target_soc_winter: !input target_soc_winter
  target_soc_summer: !input target_soc_summer
  battery_capacity_kwh: !input battery_capacity_kwh
  charge_power_kw: !input charge_power_kw
  safety_factor: !input safety_factor
  max_price_cap: !input max_price_cap
  emergency_soc: !input emergency_soc

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id: !input frank_price_sensor
  # Trigger ook direct als de Boost knop omgaat
  - platform: state
    entity_id: !input boost_switch
    to: "on"

action:
  - variables:
      current_soc: "{{ states(battery_soc_sensor) | float(0) }}"
      current_price: "{{ states(frank_price_sensor) | float(0) }}"
      is_boost_active: "{{ boost_switch != [] and is_state(boost_switch, 'on') }}"
      
      # LOGICA 1: Zon & Doel
      forecast_tomorrow_val: "{{ states(solar_forecast_tomorrow) | float(0) }}"
      relevant_solar: >-
        {% if now().hour >= 14 %} {{ forecast_tomorrow_val }}
        {% else %} {{ states(solar_forecast_today) | float(0) }}
        {% endif %}
      
      dynamic_target_soc: >-
        {% if relevant_solar > summer_solar_threshold %} {{ target_soc_summer }}
        {% else %} {{ target_soc_winter }}
        {% endif %}

      # LOGICA 2: Uren Berekenen
      hours_calc: >-
        {% set soc_deficit = dynamic_target_soc - current_soc %}
        {% if soc_deficit > 0 %}
           {% set kwh_needed = (soc_deficit / 100.0) * battery_capacity_kwh %}
           {% set strict = (kwh_needed / charge_power_kw) | round(0, 'ceil') | int %}
           {% set safe = (strict * safety_factor) | round(0, 'ceil') | int %}
           {"strict": {{ strict }}, "safe": {{ safe }}}
        {% else %}
           {"strict": 0, "safe": 0}
        {% endif %}
      hours_strict: "{{ hours_calc.strict }}"
      hours_safe: "{{ hours_calc.safe }}"

      # LOGICA 3: Prijzen & Gemiddelde
      price_data: >-
        {% set raw_prices = state_attr(frank_price_sensor, 'prices') %}
        {% set output = namespace(list=[], avg=0) %}
        {% if raw_prices %}
           {% set text = raw_prices | string %}
           {% set matches = text | regex_findall("from_hour': (\\d+).*?price': ([0-9.]+)") %}
           {% for m in matches %}
              {% set output.list = output.list + [m[1]|float] %}
           {% endfor %}
        {% endif %}
        {% if output.list | length > 0 %}
          {% set output.avg = (output.list | sum / output.list | length) %}
        {% endif %}
        {"list": {{ output.list }}, "avg": {{ output.avg }}}
      
      sorted_prices: "{{ price_data.list | sort }}"
      avg_price: "{{ price_data.avg }}"

      # LOGICA 4: Drempels & Rendement
      # Bereken de maximale prijs waarbij we nog "winst" maken t.o.v. gemiddelde
      # Formule: Gemiddelde * (1 - marge/100).
      # Voorbeeld: 0.30 * (1 - 0.20) = 0.24.
      profit_price_limit: "{{ avg_price * (1 - (min_profit_margin / 100)) }}"

      # Drempel Strict (Must run)
      threshold_strict: >-
        {% if sorted_prices | length > 0 and hours_strict > 0 %}
           {% set idx = (hours_strict - 1) if (hours_strict - 1) < sorted_prices|length else (sorted_prices|length - 1) %}
           {{ sorted_prices[idx] }}
        {% else %} -999 {% endif %}

      # Drempel Safe (Alleen als goedkoop)
      threshold_safe: >-
        {% if sorted_prices | length > 0 and hours_safe > 0 %}
           {% set idx = (hours_safe - 1) if (hours_safe - 1) < sorted_prices|length else (sorted_prices|length - 1) %}
           {{ sorted_prices[idx] }}
        {% else %} -999 {% endif %}

  - choose:
      # SCENARIO 1: BOOST MODUS (Handmatig)
      - conditions:
          - condition: template
            value_template: "{{ is_boost_active }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - if:
                  - condition: template
                    value_template: "{{ notify_device != [] }}"
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: "ðŸš€ Boost geactiveerd! Batterij gaat geforceerd laden."

      # SCENARIO 2: NOOD (Batterij kritiek)
      - conditions:
          - condition: template
            value_template: "{{ current_soc < emergency_soc }}"
          - condition: template
            value_template: "{{ current_price < (max_price_cap * 1.5) }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - if:
                  - condition: template
                    value_template: "{{ notify_device != [] }}"
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: "âš ï¸ Noodlading gestart (SoC < {{ emergency_soc }}%)."

      # SCENARIO 3: SLIM LADEN (Met Rendementscheck)
      - conditions:
          - condition: or
            conditions:
              # A: Strikte uren (De goedkoopste uren die we ECHT nodig hebben)
              - condition: template
                value_template: "{{ current_price <= threshold_strict }}"
              
              # B: Buffer uren (Alleen als prijs lager is dan Winst-limiet)
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ current_price <= threshold_safe }}"
                  - condition: template
                    # HIER ZIT DE NIEUWE RENDEMENTSCHECK:
                    value_template: "{{ current_price < profit_price_limit }}"
          
          # Algemene checks
          - condition: template
            value_template: "{{ current_price < max_price_cap }}"
          - condition: template
            value_template: "{{ current_soc < dynamic_target_soc }}"
        sequence:
          # Alleen Actie ondernemen als hij nog UIT staat (anti-spam)
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              # Notificatie
              - if:
                  - condition: template
                    value_template: "{{ notify_device != [] }}"
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: >-
                      ðŸ”‹ Slim laden gestart! 
                      Prijs: â‚¬{{ current_price | round(3) }}.
                      Doel: {{ dynamic_target_soc }}%.
                      Reden: {{ 'Strikt noodzakelijk' if current_price <= threshold_strict else 'Buffer (Goede prijs)' }}

      # SCENARIO 4: STOPPEN
      - conditions:
          - condition: template
            value_template: "{{ is_state(battery_reserve_switch, 'on') }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input battery_reserve_switch

mode: single