blueprint:
  name: Frank Energie - V10 (Met Uitleg)
  description: >
    Slim laden voor Frank Energie.
    
    Deze automatisering probeert de perfecte balans te vinden tussen:
    1. Goedkoop laden (prijzen laag).
    2. Ruimte vrijhouden voor gratis zon (zomermodus).
    3. Genoeg lading hebben voor de dure piekuren (wintermodus).
    
    Het script kijkt naar de prijzen van vandaag én morgen, en past de laadstrategie aan op basis van de zonvoorspelling.
  domain: automation
  input:
    battery_reserve_switch:
      name: Reserve mode switch
      description: De schakelaar die het laden vanaf het net forceert (bijv. 'Force Charge' of 'Reserve Mode').
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: Batterij SoC sensor (%)
      selector:
        entity:
          domain: sensor
          device_class: battery
    frank_price_sensor:
      name: Frank Energie prijs sensor
      description: De sensor die de toekomstige prijzen bevat (attribuut 'prices').
      selector:
        entity:
          domain: sensor

    # --- ZON SENSORS ---
    solar_forecast_today:
      name: Zonvoorspelling VANDAAG (kWh)
      description: Hoeveel wekt de zon vandaag op? (Wordt overdag gebruikt).
      selector:
        entity:
          domain: sensor
    solar_forecast_tomorrow:
      name: Zonvoorspelling MORGEN (kWh)
      description: Hoeveel wekt de zon morgen op? (Wordt in de avond/nacht gebruikt voor planning).
      selector:
        entity:
          domain: sensor

    # --- SEIZOENSMANAGEMENT (DE UITLEG) ---
    summer_solar_threshold:
      name: Omschakelpunt Zomer/Winter (kWh)
      description: >
        Boven hoeveel kWh zonopbrengst beschouw je de dag als 'zonnig'?
        Hierboven gebruikt hij het Zomer Doel (ruimte vrijhouden).
        Hieronder gebruikt hij het Winter Doel (volgooien).
        Advies: 10-15 kWh.
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "kWh"

    target_soc_winter:
      name: Doel SoC Winter / Donkere dag (%)
      description: >
        WAAROM: Op donkere dagen wil je de batterij 's nachts goedkoop volladen, omdat de zon het overdag niet gaat redden. Zo vermijd je dure stroom in de avondpiek.
        ADVIES: Zet dit hoog (80% - 100%).
      default: 90
      selector:
        number:
          min: 10
          max: 100

    target_soc_summer:
      name: Doel SoC Zomer / Zonnige dag (%)
      description: >
        WAAROM: Als de zon morgen fel schijnt, is het zonde als je batterij al vol zit met netstroom. Je wilt ruimte vrijhouden voor gratis zonne-energie. Laad 's nachts alleen genoeg om de ochtend (tot zonsopkomst) te overleven.
        ADVIES: Zet dit laag (20% - 40%).
      default: 30
      selector:
        number:
          min: 10
          max: 100

    # --- SYSTEEM CONFIGURATIE ---
    battery_capacity_kwh:
      name: Batterij Capaciteit (kWh)
      description: Totale grootte van je batterij. Nodig om te berekenen hoe lang het laden duurt.
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 0.1
          unit_of_measurement: "kWh"
    charge_power_kw:
      name: Normale Laadsnelheid (kW)
      description: De snelheid waarmee je systeem laadt.
      default: 3.0
      selector:
        number:
          min: 0.1
          max: 22
          step: 0.1
          unit_of_measurement: "kW"
    safety_factor:
      name: BMS Vertragingsfactor
      description: >
        Soms laadt een batterij traag (koud weer / balanceren).
        1.0 = Precies berekenen (Risico: batterij komt niet vol).
        1.5 = 50% extra tijd reserveren (Veilig: stopt vanzelf als hij vol is).
        Gebruik 2.0 als je vaak last hebt van traag laden (500W).
      default: 1.5
      selector:
        number:
          min: 1.0
          max: 4.0
          step: 0.1

    # --- BEVEILIGING ---
    max_price_cap:
      name: Absolute Max Prijs (€)
      description: Zelfs als de batterij leeg is, NOOIT laden als de prijs hierboven komt.
      default: 0.35
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.01
    emergency_soc:
      name: Nood SoC (%)
      description: Als de batterij hieronder zakt, wordt ALTIJD geladen (tot max prijs). Voorkomt uitval.
      default: 10
      selector:
        number:
          min: 0
          max: 100

variables:
  battery_reserve_switch: !input battery_reserve_switch
  battery_soc_sensor: !input battery_soc_sensor
  frank_price_sensor: !input frank_price_sensor
  solar_forecast_today: !input solar_forecast_today
  solar_forecast_tomorrow: !input solar_forecast_tomorrow
  summer_solar_threshold: !input summer_solar_threshold
  target_soc_winter: !input target_soc_winter
  target_soc_summer: !input target_soc_summer
  max_price_cap: !input max_price_cap
  emergency_soc: !input emergency_soc
  battery_capacity_kwh: !input battery_capacity_kwh
  charge_power_kw: !input charge_power_kw
  safety_factor: !input safety_factor

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id: !input frank_price_sensor

action:
  - variables:
      current_soc: "{{ states(battery_soc_sensor) | float(0) }}"
      current_price: "{{ states(frank_price_sensor) | float(0) }}"
      forecast_today_val: "{{ states(solar_forecast_today) | float(0) }}"
      forecast_tomorrow_val: "{{ states(solar_forecast_tomorrow) | float(0) }}"
      
      # LOGICA: Gebruik morgen's voorspelling als het al later op de dag is (na 14u)
      relevant_solar_forecast: >-
        {% if now().hour >= 14 %}
          {{ forecast_tomorrow_val }}
        {% else %}
          {{ forecast_today_val }}
        {% endif %}
      
      # LOGICA: Bepaal doel op basis van die voorspelling
      dynamic_target_soc: >-
        {% if relevant_solar_forecast > summer_solar_threshold %}
          {{ target_soc_summer }}
        {% else %}
          {{ target_soc_winter }}
        {% endif %}
      
      # BEREKENING: Hoeveel kWh en hoeveel uur hebben we nodig?
      hours_calc: >-
        {% set soc_deficit = dynamic_target_soc - current_soc %}
        {% if soc_deficit > 0 %}
           {% set kwh_needed = (soc_deficit / 100.0) * battery_capacity_kwh %}
           {% set strict = (kwh_needed / charge_power_kw) | round(0, 'ceil') | int %}
           {% set safe = (strict * safety_factor) | round(0, 'ceil') | int %}
           {"strict": {{ strict }}, "safe": {{ safe }}}
        {% else %}
           {"strict": 0, "safe": 0}
        {% endif %}

      hours_strict: "{{ hours_calc.strict }}"
      hours_safe: "{{ hours_calc.safe }}"

      # PRIJZEN: Haal op en bereken gemiddelde
      price_data: >-
        {% set raw_prices = state_attr(frank_price_sensor, 'prices') %}
        {% set output = namespace(list=[], avg=0) %}
        {% if raw_prices %}
           {% set text = raw_prices | string %}
           {% set matches = text | regex_findall("from_hour': (\\d+).*?price': ([0-9.]+)") %}
           {% for m in matches %}
              {% set output.list = output.list + [m[1]|float] %}
           {% endfor %}
        {% endif %}
        {% if output.list | length > 0 %}
          {% set output.avg = (output.list | sum / output.list | length) %}
        {% endif %}
        {"list": {{ output.list }}, "avg": {{ output.avg }}}

      sorted_prices: "{{ price_data.list | sort }}"
      avg_price: "{{ price_data.avg }}"

      # DREMPELS: Bepaal de maximumprijs voor 'strict' en 'safe' laden
      threshold_strict: >-
        {% if sorted_prices | length > 0 and hours_strict > 0 %}
           {% set limit_idx = sorted_prices|length - 1 %}
           {% set target_idx = (hours_strict - 1) %}
           {% set final_idx = target_idx if target_idx <= limit_idx else limit_idx %}
           {{ sorted_prices[final_idx] }}
        {% else %}
           -999
        {% endif %}

      threshold_safe: >-
        {% if sorted_prices | length > 0 and hours_safe > 0 %}
           {% set limit_idx = sorted_prices|length - 1 %}
           {% set target_idx = (hours_safe - 1) %}
           {% set final_idx = target_idx if target_idx <= limit_idx else limit_idx %}
           {{ sorted_prices[final_idx] }}
        {% else %}
           -999
        {% endif %}

  - choose:
      # SCENARIO 1: NOOD (Batterij bijna leeg)
      - conditions:
          - condition: template
            value_template: "{{ current_soc < emergency_soc }}"
          - condition: template
            value_template: "{{ current_price < (max_price_cap * 1.5) }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch

      # SCENARIO 2: SLIM LADEN
      - conditions:
          - condition: or
            conditions:
              # Optie A: Prijs is zo laag dat hij in de 'Strikte' planning valt (Must run)
              - condition: template
                value_template: "{{ current_price <= threshold_strict }}"
              # Optie B: Prijs is in de 'Buffer' zone (Safe run) EN lager dan gemiddeld
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ current_price <= threshold_safe }}"
                  - condition: template
                    value_template: "{{ current_price < avg_price }}"
          # Veiligheidschecks
          - condition: template
            value_template: "{{ current_price < max_price_cap }}"
          - condition: template
            value_template: "{{ current_soc < dynamic_target_soc }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch

      # SCENARIO 3: STOPPEN (Als niet aan bovenstaande wordt voldaan)
      - conditions:
          - condition: template
            value_template: "{{ is_state(battery_reserve_switch, 'on') }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input battery_reserve_switch

mode: single