blueprint:
  name: Slimme batterij laadplanning met dynamische tijd en gemiddelde prijs
  description: Laadt automatisch de batterij op de goedkoopste momenten op basis van actuele prijzen en gemiddelde prijs per blok.
  domain: automation
  input:
    battery_reserve_switch:
      name: Reserve mode switch
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: Batterij SOC sensor
      selector:
        entity:
          domain: sensor
    electricity_price_sensor:
      name: Huidige elektriciteitsprijs
      selector:
        entity:
          domain: sensor
    solar_forecast_sensor:
      name: Verwachte zonopbrengst (kWh)
      default: ""
      selector:
        entity:
          domain: sensor
    min_solar_day:
      name: Minimale zon kWh voor dagladen
      default: 8
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: "kWh"
    load_start_hour:
      name: Start uur controleren
      default: 0
      selector:
        number:
          min: 0
          max: 23
    load_end_hour:
      name: Eind uur controleren
      default: 23
      selector:
        number:
          min: 0
          max: 23

variables:
  battery_reserve_switch: !input battery_reserve_switch
  battery_soc_sensor: !input battery_soc_sensor
  electricity_price_sensor: !input electricity_price_sensor
  solar_forecast_sensor: !input solar_forecast_sensor
  min_solar_day: !input min_solar_day
  load_start_hour: !input load_start_hour
  load_end_hour: !input load_end_hour

trigger:
  - platform: time_pattern
    minutes: "/5"

action:
  - variables:
      blocks: "{{ state_attr(electricity_price_sensor, 'prices') }}"
      prices: >
        {% if blocks %}
          {{ blocks | map(attribute='price') | map('float') | list }}
        {% else %}
          []
        {% endif %}
      avg_day: >
        {% if prices|length > 0 %}
          {{ (prices | sum / prices|length) | round(4) }}
        {% else %}
          none
        {% endif %}
      avg_night: >
        {% if prices|length >= 8 %}
          {{ (prices[0:7] | sum / 7) | round(4) }}
        {% else %}
          none
        {% endif %}
      avg_dayblock: >
        {% if prices|length >= 16 %}
          {{ (prices[11:15] | sum / 4) | round(4) }}
        {% else %}
          none
        {% endif %}
      current_price: "{{ states(electricity_price_sensor) | float }}"
      current_hour: "{{ now().hour }}"

  - choose:
      # Laden op basis van gemiddelde prijs en SOC
      - conditions:
          - condition: numeric_state
            entity_id: !input battery_soc_sensor
            below: 100
          - condition: template
            value_template: >
              {% if current_hour >= load_start_hour and current_hour <= load_end_hour %}
                {% if current_hour >=0 and current_hour < 7 %}
                  {{ avg_night is not none and current_price < avg_night }}
                {% elif current_hour >=11 and current_hour < 15 %}
                  {{ avg_dayblock is not none and current_price < avg_dayblock }}
                {% else %}
                  {{ avg_day is not none and current_price < avg_day }}
                {% endif %}
              {% else %}
                false
              {% endif %}
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            below: !input min_solar_day
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch

      # Stoppen als te duur of batterij vol
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: !input battery_soc_sensor
                above: 99
              - condition: template
                value_template: >
                  {% if current_hour >=0 and current_hour < 7 %}
                    {{ avg_night is not none and current_price >= avg_night }}
                  {% elif current_hour >=11 and current_hour < 15 %}
                    {{ avg_dayblock is not none and current_price >= avg_dayblock }}
                  {% else %}
                    {{ avg_day is not none and current_price >= avg_day }}
                  {% endif %}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input battery_reserve_switch
