blueprint:
  name: "Frank Energie - V22 (Midnight Fix)"
  description: >
    Opgelost: Problemen met tijdsloten over middernacht (bijv. 21:00 tot 06:00).
    
    FIXES:
    - Midnight Logic: Snapt dat 23:00 in een blok van 21:00-06:00 valt.
    - Past Filter: Negeert prijzen die in het verleden liggen (zodat je geen oude data gebruikt).
    - From-Key & UTC correcties inbegrepen.
  domain: automation
  input:
    # --- TIJDSLOTEN ---
    night_start:
      name: "Starttijd Nachtladen"
      default: "00:00:00"
      selector:
        time:
    night_end:
      name: "Eindtijd Nachtladen"
      default: "06:00:00"
      selector:
        time:
    day_start:
      name: "Starttijd Middagladen"
      default: "12:00:00"
      selector:
        time:
    day_end:
      name: "Eindtijd Middagladen"
      default: "15:00:00"
      selector:
        time:

    # --- BASIS ENTITEITEN ---
    battery_reserve_switch:
      name: "Schakelaar: Geforceerd Laden"
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: "Sensor: Batterij SoC (%)"
      selector:
        entity:
          domain: sensor
          device_class: battery
    frank_price_sensor:
      name: "Sensor: Frank Energie Prijzen"
      selector:
        entity:
          domain: sensor

    # --- BOOST & NOTIFICATIES ---
    boost_switch:
      name: "Optie: Boost Schakelaar"
      default: []
      selector:
        entity:
          domain: input_boolean
    notify_device:
      name: "Optie: Telefoon voor meldingen"
      default: []
      selector:
        device:
          integration: mobile_app

    # --- ZON & SEIZOEN ---
    solar_forecast_today:
      name: "Sensor: Zon VANDAAG"
      selector:
        entity:
          domain: sensor
    solar_forecast_tomorrow:
      name: "Sensor: Zon MORGEN"
      selector:
        entity:
          domain: sensor
    summer_solar_threshold:
      name: "Drempel Zonnige Dag (kWh)"
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "kWh"

    # --- RENDEMENT & DOELEN ---
    min_profit_margin:
      name: "Minimale Winstmarge (%)"
      default: 20
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: "%"
    target_soc_winter:
      name: "Doel SoC Winter (%)"
      default: 90
      selector:
        number:
          min: 10
          max: 100
    target_soc_summer:
      name: "Doel SoC Zomer (%)"
      default: 30
      selector:
        number:
          min: 10
          max: 100

    # --- SYSTEEM ---
    battery_capacity_kwh:
      name: "Batterij Capaciteit (kWh)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 0.1
    charge_power_kw:
      name: "Laadsnelheid (kW)"
      default: 3.0
      selector:
        number:
          min: 0.1
          max: 22
          step: 0.1
    safety_factor:
      name: "BMS Vertragingsfactor"
      default: 1.5
      selector:
        number:
          min: 1.0
          max: 4.0
          step: 0.1
    max_price_cap:
      name: "Absolute Max Prijs (â‚¬)"
      default: 0.35
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.01
          mode: box
          unit_of_measurement: "â‚¬"
    emergency_soc:
      name: "Nood SoC (%)"
      default: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

variables:
  # Inputs
  battery_reserve_switch: !input battery_reserve_switch
  battery_soc_sensor: !input battery_soc_sensor
  frank_price_sensor: !input frank_price_sensor
  boost_switch: !input boost_switch
  notify_device: !input notify_device
  # Tijdsloten
  night_start: !input night_start
  night_end: !input night_end
  day_start: !input day_start
  day_end: !input day_end
  # Overige
  solar_forecast_today: !input solar_forecast_today
  solar_forecast_tomorrow: !input solar_forecast_tomorrow
  summer_solar_threshold: !input summer_solar_threshold
  min_profit_margin: !input min_profit_margin
  target_soc_winter: !input target_soc_winter
  target_soc_summer: !input target_soc_summer
  battery_capacity_kwh: !input battery_capacity_kwh
  charge_power_kw: !input charge_power_kw
  safety_factor: !input safety_factor
  max_price_cap: !input max_price_cap
  emergency_soc: !input emergency_soc

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id: !input frank_price_sensor
  - platform: state
    entity_id: !input boost_switch
    to: "on"

action:
  - variables:
      current_soc: "{{ states(battery_soc_sensor) | float(0) }}"
      current_price: "{{ states(frank_price_sensor) | float(0) }}"
      is_boost_active: "{{ boost_switch != [] and is_state(boost_switch, 'on') }}"

      # --- 1. SLIMME TIJDSLOT LOGICA ---
      # We moeten weten of een slot over middernacht gaat (Start > Eind)
      ns = night_start.split(':')[0] | int
      ne = night_end.split(':')[0] | int
      ds = day_start.split(':')[0] | int
      de = day_end.split(':')[0] | int
      
      night_crosses = (ns > ne)
      day_crosses = (ds > de)
      
      # Huidige tijd check
      now_h = now().hour
      
      # Check of we NU in het nachtblok zitten (rekening houdend met middernacht)
      is_night_now: >-
        {% if night_crosses %} {{ now_h >= ns or now_h < ne }}
        {% else %} {{ now_h >= ns and now_h < ne }}
        {% endif %}

      # Check of we NU in het middagblok zitten
      is_day_now: >-
        {% if day_crosses %} {{ now_h >= ds or now_h < de }}
        {% else %} {{ now_h >= ds and now_h < de }}
        {% endif %}
      
      is_in_slot: "{{ is_night_now or is_day_now }}"

      # --- 2. DATA PARSING (Met Timestamp voor History Filter) ---
      raw: "{{ state_attr(frank_price_sensor, 'prices') }}"
      prices_json: >-
        {% if raw %}
          {% set text = raw | string %}
          {% set matches = text | regex_findall(
            "datetime\\.datetime\\((\\d+), (\\d+), (\\d+), (\\d+), (\\d+).*?price': ([0-9.]+)"
          ) %}
          [
          {%- for m in matches %}
            {% set y = m[0]|int %}
            {% set mo = m[1]|int %}
            {% set d = m[2]|int %}
            {% set h = m[3]|int %}
            {% set mn = m[4]|int %}
            {% set price = m[5]|float %}
            
            {% set iso_utc = "%04d-%02d-%02dT%02d:%02d:00+00:00" | format(y, mo, d, h, mn) %}
            {% set local_dt = iso_utc | as_datetime | as_local %}
            
            {
              "local_hour": {{ local_dt.hour }},
              "ts": {{ as_timestamp(local_dt) }},
              "price": {{ price }}
            }{{ "," if not loop.last }}
          {%- endfor %}
          ]
        {% else %} [] {% endif %}

      # --- 3. FILTEREN (FUTURE ONLY & MIDNIGHT AWARE) ---
      filtered_data: >-
        {% set output = namespace(list=[], avg=0) %}
        {% set now_ts = as_timestamp(now()) %}
        
        {# Buffer van 1 uur in het verleden toestaan (zodat 21:05 nog steeds 21:00 ziet) #}
        {% set history_cutoff = now_ts - 3600 %}
        
        {% if prices_json %}
           {% for item in prices_json %}
              {% set p_hour = item.local_hour %}
              {% set p_ts = item.ts %}
              {% set p_price = item.price %}
              
              {# A. FILTER VERLEDEN: Negeer prijzen ouder dan 1 uur geleden #}
              {% if p_ts >= history_cutoff %}
              
                  {# B. FILTER TIJDSLOT: Valt dit uur in Nacht of Middag? #}
                  {% set in_night = false %}
                  {% if night_crosses %}
                    {% set in_night = (p_hour >= ns or p_hour < ne) %}
                  {% else %}
                    {% set in_night = (p_hour >= ns and p_hour < ne) %}
                  {% endif %}
                  
                  {% set in_day = false %}
                  {% if day_crosses %}
                    {% set in_day = (p_hour >= ds or p_hour < de) %}
                  {% else %}
                    {% set in_day = (p_hour >= ds and p_hour < de) %}
                  {% endif %}

                  {# Als het in een geldig slot valt, voeg toe aan de lijst #}
                  {% if in_night or in_day %}
                     {% set output.list = output.list + [p_price] %}
                  {% endif %}
                  
              {% endif %}
           {% endfor %}

           {% if output.list | length > 0 %}
              {% set output.avg = (output.list | sum / output.list | length) %}
           {% endif %}
        {% endif %}
        
        {"list": {{ output.list }}, "avg": {{ output.avg }}}

      sorted_prices: "{{ filtered_data.list | sort }}"
      avg_price: "{{ filtered_data.avg }}"
      profit_price_limit: "{{ avg_price * (1 - (min_profit_margin / 100)) }}"

      # --- 4. ZON & DOEL ---
      forecast_tomorrow_val: "{{ states(solar_forecast_tomorrow) | float(0) }}"
      relevant_solar: >-
        {% if now().hour >= 14 %} {{ forecast_tomorrow_val }}
        {% else %} {{ states(solar_forecast_today) | float(0) }}
        {% endif %}
      dynamic_target_soc: >-
        {% if relevant_solar > summer_solar_threshold %} {{ target_soc_summer }}
        {% else %} {{ target_soc_winter }}
        {% endif %}

      # --- 5. UREN BEREKENEN ---
      hours_calc: >-
        {% set soc_deficit = dynamic_target_soc - current_soc %}
        {% if soc_deficit > 0 %}
           {% set kwh_needed = (soc_deficit / 100.0) * battery_capacity_kwh %}
           {% set strict = (kwh_needed / charge_power_kw) | round(0, 'ceil') | int %}
           {% set safe = (strict * safety_factor) | round(0, 'ceil') | int %}
           {"strict": {{ strict }}, "safe": {{ safe }}}
        {% else %}
           {"strict": 0, "safe": 0}
        {% endif %}
      hours_strict: "{{ hours_calc.strict }}"
      hours_safe: "{{ hours_calc.safe }}"

      # --- 6. DREMPELS ---
      threshold_strict: >-
        {% if sorted_prices | length > 0 and hours_strict > 0 %}
           {% set idx = (hours_strict - 1) if (hours_strict - 1) < sorted_prices|length else (sorted_prices|length - 1) %}
           {{ sorted_prices[idx] }}
        {% else %} -999 {% endif %}

      threshold_safe: >-
        {% if sorted_prices | length > 0 and hours_safe > 0 %}
           {% set idx = (hours_safe - 1) if (hours_safe - 1) < sorted_prices|length else (sorted_prices|length - 1) %}
           {{ sorted_prices[idx] }}
        {% else %} -999 {% endif %}

  - choose:
      # SCENARIO 1: BOOST
      - conditions:
          - condition: template
            value_template: "{{ is_boost_active }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - if:
                  - condition: template
                    value_template: "{{ notify_device != [] }}"
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: "ðŸš€ Boost geactiveerd!"

      # SCENARIO 2: NOOD
      - conditions:
          - condition: template
            value_template: "{{ current_soc < emergency_soc }}"
          - condition: template
            value_template: "{{ current_price < (max_price_cap * 1.5) }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - if:
                  - condition: template
                    value_template: "{{ notify_device != [] }}"
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: "âš ï¸ Noodlading gestart."

      # SCENARIO 3: SLIM LADEN
      - conditions:
          # A: Binnen Tijdslot (Nu met correcte Midnight Logic)
          - condition: template
            value_template: "{{ is_in_slot }}"
          
          # B: Prijscondities
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ current_price <= threshold_strict }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ current_price <= threshold_safe }}"
                  - condition: template
                    value_template: "{{ current_price < profit_price_limit }}"
          
          # C: Veiligheid
          - condition: template
            value_template: "{{ current_price < max_price_cap }}"
          - condition: template
            value_template: "{{ current_soc < dynamic_target_soc }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - if:
                  - condition: template
                    value_template: "{{ notify_device != [] }}"
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: >-
                      ðŸ”‹ Slim laden gestart! 
                      Prijs: â‚¬{{ current_price | round(3) }}.
                      Blokgemiddelde: â‚¬{{ avg_price | round(3) }}.
                      Doel: {{ dynamic_target_soc }}%.

      # SCENARIO 4: STOPPEN
      - conditions:
          - condition: template
            value_template: "{{ is_state(battery_reserve_switch, 'on') }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input battery_reserve_switch

mode: single